name: Depoly html page to fast-fire server
on:
  push:
    branches:
      - gh-page
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - name: Create Workspace
        run: |
          export REPO=$(basename $GITHUB_REPOSITORY) &&
          cd $GITHUB_WORKSPACE/.. && mkdir src/ &&
          mv $REPO/ src/ && mkdir $REPO/ && mv src/ $REPO/ && cd $REPO/
      - name: Deploy
        run: |
          export REPO=$(basename $GITHUB_REPOSITORY) &&
          cd $GITHUB_WORKSPACE/src &&
          sshpass -p ${{ secrets.USER_PASS }} scp -r ./$REPO ${{ secrets.USER_NAME }}@${{ secrets.USER_HOST }}:/home/${{ secrets.USER_NAME }}/test/$REPO
